# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZZQRCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod ‘Masonry’
pod 'SVProgressHUD'
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh'
  # Pods for ZZQRCode


end
